const mongoose = require('mongoose');

const fyRowSchema = new mongoose.Schema({
  billNo: { type: String, required: true, unique: true },
  billType: { type: String, default: 'FREIGHT' },
  editedInvoiceDate: { type: String },
  editedInvoiceNumber: { type: String },
  editedMonth: { type: String },
  editedSite: { type: String },
  editedAmount: { type: Number },
  shipmentNo: { type: String },
  cgst: { type: Number },
  sgst: { type: Number },
  totalAmount: { type: Number },
  tds: { type: Number },
  receivable: { type: Number },
  paymentAmount: { type: Number },
  tdsProvision: { type: Number },
  paymentDate: { type: String },
  referenceNo: { type: String },
  debitAmount: { type: Number },
  debitReason: { type: String, default: 'None' },
  debitReasons: { type: [String], default: [] },
  remarks: { type: String },
  // Legacy singular fields (kept for backward compat)
  damageVehicle: { type: String },
  damageTrip: { type: Object },
  // New plural fields used by the Damage/Shortage modal
  damageYear: { type: String },
  damageMonth: { type: String },
  damageVehicles: { type: [String], default: [] },
  damageTrips: { type: mongoose.Schema.Types.Mixed, default: [] },
  damageVehicleAmounts: { type: mongoose.Schema.Types.Mixed, default: {} },
  // Deduction Allocation Fields
  originalDebitAmount: { type: Number },
  totalAllocatedAmount: { type: Number, default: 0 },
  remainingDebitAmount: { type: Number },
  deductionAllocations: [{
    allocationId: { type: String, required: true },
    bankBookRecordId: { type: String },
    invoiceNumber: { type: String },
    debitReason: { type: String, required: true },
    financialYear: { type: String },
    months: [{ type: String }],
    vehicles: [{ type: String }],
    condition: { type: String },
    originalDebitAmount: { type: Number },
    allocatedAmount: { type: Number, required: true },
    remainingDebitAmount: { type: Number },
    allocationDate: { type: String },
    tripAllocations: [{
      tripAllocationId: { type: String },
      allocationId: { type: String },
      bankBookRecordId: { type: String },
      invoiceNumber: { type: String },
      shipmentNo: { type: String },
      invoiceNo: { type: String },
      tripRecordId: { type: String },
      tripId: { type: String },
      debitReason: { type: String },
      financialYear: { type: String },
      month: { type: String },
      vehicleNumber: { type: String },
      vehicle: { type: String },
      loadingDate: { type: String },
      originalDebitAmount: { type: Number },
      tripAllocateAmount: { type: Number },
      allocatedAmount: { type: Number },
      totalAllocatedAmount: { type: Number },
      remainingDebitAmount: { type: Number },
      createdAt: { type: Date, default: Date.now },
      updatedAt: { type: Date, default: Date.now }
    }],
    createdAt: { type: Date, default: Date.now },
    updatedAt: { type: Date, default: Date.now }
  }],
  slNo: { type: Number },
  b2bEntryId: { type: String },
  b2bEntryIds: [{ type: String }],
  hidden: { type: Boolean, default: false }
}, { timestamps: true, strict: false });

module.exports = mongoose.model('FinancialYearRow', fyRowSchema);
